# Generated by Django 4.2.16 on 2024-10-23 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('preptime_days', models.IntegerField()),
                ('preptime_hours', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('isAvailable', models.BooleanField()),
                ('NAmessage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField()),
                ('date_delivery', models.DateTimeField()),
                ('status', models.CharField(choices=[('NORD', 'NOT_ORDERED'), ('ORD', 'ORDERED'), ('REJ', 'REJECTED'), ('PAID', 'PAID'), ('FIN', 'FINISHED')], default='NORD', max_length=4)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('orderItemMessage', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elzkitchenapp.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elzkitchenapp.product')),
            ],
        ),
    ]
