# Generated by Django 4.2.16 on 2024-10-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elzkitchenapp', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('NORD', 'NOT_ORDERED'), ('ORD', 'ORDERED'), ('REJ', 'REJECTED'), ('CANC', 'CANCELLED'), ('PAID', 'PAID'), ('FIN', 'FINISHED')], default='NORD', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
