# Generated by Django 4.2.16 on 2024-10-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elzkitchenapp', '0003_alter_orders_status_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='NAmessage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
