# Generated by Django 4.2.16 on 2024-10-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elzkitchenapp', '0004_alter_product_namessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
