# Generated by Django 4.2.16 on 2024-10-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elzkitchenapp', '0005_orders_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status_msg',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
