# Generated by Django 4.2.16 on 2024-11-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elzkitchenapp', '0008_productcategory_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('items', models.TextField()),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('FINISHED', 'Finished'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='FINISHED', max_length=20)),
            ],
            options={
                'verbose_name': 'Order History',
                'verbose_name_plural': 'Order Histories',
            },
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('NORD', 'NOT_ORDERED'), ('ORD', 'ORDERED'), ('APR', 'APPROVED'), ('REJ', 'REJECTED'), ('CANC', 'CANCELLED'), ('PAID', 'PAID'), ('FIN', 'FINISHED')], default='NORD', max_length=4),
        ),
    ]
