# Generated by Django 4.2.16 on 2024-12-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elzkitchenapp', '0009_orderhistory_alter_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='orderId',
            new_name='order_id',
        ),
    ]
