# Generated by Django 4.2.16 on 2024-12-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elzkitchenapp', '0010_rename_orderid_orderhistory_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='NAmessage',
            field=models.CharField(blank=True, default='Produk baru!', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='isAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='preptime_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='preptime_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='placeholders/noImage.png', upload_to='products/'),
        ),
    ]
