# Generated by Django 4.2.16 on 2025-01-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elzkitchenapp', '0011_alter_product_namessage_alter_product_isavailable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='kitchenInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchenContact', models.CharField(blank=True, max_length=15, null=True)),
                ('kitchenOpen', models.BooleanField()),
            ],
        ),
    ]
