# Generated by Django 4.2.16 on 2025-02-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elzkitchenapp', '0013_product_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
